import { Game,cloneBoard,type Move,type Save } from '../game/core/index.js';
import { BoardRenderer } from '../demo/BoardRenderer.js';
import { AudioService } from '../demo/AudioService.js';
const el=<T extends HTMLElement=HTMLElement>(id:string):T=>document.getElementById(id) as T;
interface Run {sessionId:string|null;seed:number;save:Save;moves:Move[];expiresAt:string|null;submitted:boolean}
let api='',auth='',run:Run|null=null,game=new Game(1),busy=false,selected:number|null=null,cursor=0;
const renderer=new BoardRenderer(el<HTMLCanvasElement>('board')),audio=new AudioService();let shown=game.board;
try{const settings=JSON.parse(localStorage.getItem('nightshift.basic.v1')??'{}').settings;if(settings){renderer.reduced=settings.reduced;renderer.symbols=settings.symbols;audio.volume=settings.master*settings.effects/10000;}const raw=sessionStorage.getItem('nightshift.ranked');if(raw){run=JSON.parse(raw) as Run;game=Game.restore(run.save);shown=game.board;el('continue-run').hidden=false;}auth=sessionStorage.getItem('nightshift.auth')??'';}catch{run=null;}
async function request(path:string,body?:unknown):Promise<unknown>{if(!api)throw Error('Рейтинг не подключён / Ranking unavailable');const r=await fetch(api+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+auth}:{})},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(12000)});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error??'Connection failed');return data;}
function save():void{if(run){run.save=game.snapshot();try{sessionStorage.setItem('nightshift.ranked',JSON.stringify(run));}catch{el('status').textContent='Не закрывайте вкладку: сохранение недоступно / Save unavailable';}}}
function hud():void{el('score').textContent=String(game.score);el('remaining').textContent=String(50-game.stats.moves);el('submit').hidden=game.stats.moves<50||!run?.sessionId||run.submitted;el('back').hidden=game.stats.moves<50;el('run-type').textContent=run?.sessionId?'РЕЙТИНГ / RANKED':'ТРЕНИРОВКА / PRACTICE';el<HTMLButtonElement>('hint').disabled=busy;el<HTMLButtonElement>('leave').disabled=busy;}
function play():void{if(!run)return;el('lobby').hidden=true;el('rank-game').hidden=false;game=Game.restore(run.save);shown=game.board;renderer.paused=false;renderer.draw(shown);hud();void audio.unlock();}
async function start(online:boolean):Promise<void>{if(run&&!run.submitted&&run.moves.length<50&&!confirm('Заменить текущий забег? / Replace current run?'))return;try{let data:{sessionId:string|null;seed:number;expiresAt:string|null};if(online){const initData=window.Telegram?.WebApp.initData;if(!initData)throw Error('Откройте игру через Telegram-бота / Open through Telegram');const signed=await request('/auth',{initData}) as {token:string};auth=signed.token;sessionStorage.setItem('nightshift.auth',auth);data=await request('/session',{}) as typeof data;}else data={sessionId:null,seed:Number(new Date().toISOString().slice(0,10).replaceAll('-','')),expiresAt:null};game=new Game(data.seed);run={...data,save:game.snapshot(),moves:[],submitted:false};save();play();}catch(e){el('online-status').textContent=(e as Error).message;}}
async function swap(move:Move):Promise<void>{if(busy||renderer.paused||!run||game.stats.moves>=50)return;busy=true;selected=null;renderer.selected=null;renderer.hints=[];hud();try{const result=game.swap(move);if(result.accepted){run.moves.push(move);save();for(const event of result.events){while(renderer.paused)await new Promise<void>(r=>setTimeout(r,70));audio.play(event);await renderer.animate(shown,event);shown=cloneBoard(event.board);}el('status').textContent='+'+result.scoreDelta;}else audio.invalid();}catch{el('status').textContent='Показ прерван / Playback interrupted';}finally{shown=game.board;renderer.draw(shown);busy=false;hud();if(game.stats.moves===50)el('status').textContent=run.sessionId?'Забег окончен. Отправьте результат на проверку. / Submit for verification.':'Тренировка завершена / Practice complete';}}
function choose(i:number):void{if(busy||renderer.paused)return;if(selected===null){selected=i;renderer.selected=i;renderer.draw(shown);}else{const a=selected;selected=null;void swap({from:[a%8,Math.floor(a/8)],to:[i%8,Math.floor(i/8)]});}}
const canvas=el<HTMLCanvasElement>('board');let down:{i:number;x:number;y:number}|null=null;
canvas.onpointerdown=e=>{if(e.button!==0||busy||renderer.paused)return;const r=canvas.getBoundingClientRect();down={i:Math.floor((e.clientY-r.top)/r.height*8)*8+Math.floor((e.clientX-r.left)/r.width*8),x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);};canvas.onpointercancel=()=>{down=null;};canvas.onpointerup=e=>{if(!down)return;const d=down;down=null;const dx=e.clientX-d.x,dy=e.clientY-d.y;const from:[number,number]=[d.i%8,Math.floor(d.i/8)];if(Math.max(Math.abs(dx),Math.abs(dy))>canvas.getBoundingClientRect().width/32)void swap({from,to:Math.abs(dx)>Math.abs(dy)?[from[0]+Math.sign(dx),from[1]]:[from[0],from[1]+Math.sign(dy)]});else choose(d.i);};
canvas.onkeydown=e=>{const offsets:Record<string,number>={ArrowLeft:-1,ArrowRight:1,ArrowUp:-8,ArrowDown:8};if(e.key in offsets){e.preventDefault();if(e.key==='ArrowLeft'&&cursor%8===0||e.key==='ArrowRight'&&cursor%8===7)return;cursor=Math.max(0,Math.min(63,cursor+offsets[e.key]!));renderer.hints=[cursor];renderer.draw(shown);}else if(e.key===' '||e.key==='Enter'){e.preventDefault();choose(cursor);}};
el('hint').onclick=()=>{const move=game.hint();renderer.hints=move?[move.from[1]*8+move.from[0],move.to[1]*8+move.to[0]]:[];renderer.draw(shown);};
const pause=():void=>{if(el('rank-game').hidden||el<HTMLDialogElement>('pause-dialog').open)return;renderer.paused=true;save();void audio.suspend();el<HTMLDialogElement>('pause-dialog').showModal();};const resume=():void=>{renderer.paused=false;el<HTMLDialogElement>('pause-dialog').close();void audio.unlock();};el('pause').onclick=pause;el('resume').onclick=resume;el<HTMLDialogElement>('pause-dialog').oncancel=e=>{e.preventDefault();resume();};
function lobby():void{save();el('rank-game').hidden=true;el('lobby').hidden=false;el('continue-run').hidden=!run;el<HTMLDialogElement>('pause-dialog').close();void loadBoard('day');}el('leave').onclick=lobby;el('back').onclick=lobby;el('continue-run').onclick=play;
el('start-online').onclick=()=>void start(true);el('practice').onclick=()=>void start(false);el('submit').onclick=async()=>{if(!run||busy)return;el<HTMLButtonElement>('submit').disabled=true;try{const result=await request('/submit',{sessionId:run.sessionId,moves:run.moves,score:game.score}) as {verified:boolean};if(result.verified){run.submitted=true;save();el('status').textContent='✓ Результат проверен / Verified';hud();}}catch(e){el('status').textContent=(e as Error).message;}finally{el<HTMLButtonElement>('submit').disabled=false;}};
interface Row {place:number;nickname:string;score:number;me:boolean}
async function loadBoard(period:string):Promise<void>{const root=el('leaderboard');root.replaceChildren();try{const result=await request('/leaderboard?period='+period) as {top:Row[];neighbors:Row[]};const rows=[...result.top,...result.neighbors.filter(r=>r.place>100)];if(!rows.length){root.textContent='Пока нет результатов / No results yet';return;}const table=document.createElement('table');table.style.width='100%';for(const r of rows){const tr=document.createElement('tr');for(const value of [String(r.place),r.nickname+(r.me?' ← YOU':''),r.score.toLocaleString()]){const td=document.createElement('td');td.textContent=value;td.style.padding='12px';tr.append(td);}table.append(tr);}root.append(table);}catch{root.textContent='Онлайн-рейтинг сейчас недоступен. Тренировка работает без сервера. / Ranking unavailable; practice is available.';}}
for(const b of Array.from(document.querySelectorAll<HTMLButtonElement>('[data-period]')))b.onclick=()=>void loadBoard(b.dataset.period!);
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('pagehide',save);
try{const config=await (await fetch('./runtime-config.json')).json() as {apiBase:string};api=config.apiBase.replace(/\/$/,'');if(api&&!/^https:\/\//.test(api)&&!/^http:\/\/localhost[:/]/.test(api))throw Error('Invalid API URL');if(api){await request('/health');el<HTMLButtonElement>('start-online').disabled=false;el('online-status').textContent='Для рейтинга откройте игру в Telegram / Open in Telegram to enter ranked play';}else el('online-status').textContent='Сервер рейтинга ещё не подключён. Доступна тренировка. / Practice available; ranking server not configured.';}catch{el('online-status').textContent='Нет связи с рейтингом / Ranking offline';}void loadBoard('day');
