import { Level, validateLevel, type LevelData } from './Level.js';
import { ProgressStore, type Booster } from './Progress.js';
import { BoardRenderer } from '../demo/BoardRenderer.js';
import { AudioService } from '../demo/AudioService.js';
import { MusicService } from '../app/MusicService.js';
import { cloneBoard, type Move, type Board } from '../game/core/index.js';
const el=<T extends HTMLElement=HTMLElement>(id:string):T=>document.getElementById(id) as T;
const dlg=(id:string):HTMLDialogElement=>el<HTMLDialogElement>(id);
let en=false;try{en=JSON.parse(localStorage.getItem('nightshift.basic.v1')??'{}').settings?.language==='en';}catch{/* Defaults to Russian. */}
const text=(ru:string,eng:string):string=>en?eng:ru;
const store=new ProgressStore();await store.open();
const renderer=new BoardRenderer(el<HTMLCanvasElement>('board')),audio=new AudioService(),music=new MusicService();
try{const s=JSON.parse(localStorage.getItem('nightshift.basic.v1')??'{}').settings;if(s){renderer.reduced=s.reduced;renderer.symbols=s.symbols;renderer.economical=s.quality==='low';audio.volume=s.master*s.effects/10000;music.volume=s.master*s.music/10000;}}catch{/* Optional settings. */}
let mode:'mission'|'puzzle'=new URLSearchParams(location.search).get('mode')==='puzzle'?'puzzle':'mission';let missions:LevelData[]=[],puzzles:LevelData[]=[];let game:Level|null=null;let shown:Board|undefined;let busy=false;let selected:number|null=null;let cursor=0;let armed:Booster|null=null;let confirmAction=():void=>{};let lastInput=Date.now();
const names:Record<Booster,string>={opener:text('Открывашка','Opener'),shuffle:text('Перемешать','Shuffle'),recolor:text('Шейкер','Recolor'),rocket:text('Ракета на старте','Start rocket'),bomb:text('Бомба на старте','Start bomb'),lightning:text('Молния на старте','Start lightning')};
const list=():LevelData[]=>mode==='mission'?missions:puzzles;
const profile=():void=>{el('profile-line').textContent=`LV ${1+Math.floor(store.data.xp/1000)} · ${store.data.xp} XP · ${store.data.caps} ◉ · ${store.stars} ★`;if(store.error)el('notice').textContent=text('Не удалось сохранить прогресс. Не закрывайте вкладку.','Progress could not be saved. Keep this tab open.');};
function checkpoint():void{if(game)store.data.active=game.won?null:game.snapshot();store.save();profile();}
function terrain():void{
 const root=el('terrain');root.replaceChildren();if(!game)return;
 for(const item of [...game.data.holes.map(index=>({index,type:'hole',hp:0})),...game.blockers,...game.parcels.map(index=>({index,type:'parcel',hp:0}))]){const cell=document.createElement('div');cell.className='terrain-cell '+item.type;cell.style.gridColumn=String(item.index%8+1);cell.style.gridRow=String(Math.floor(item.index/8)+1);cell.textContent=item.type==='parcel'?'↓':item.type==='hole'?'':String(item.hp);root.append(cell);}
}
function hud():void{
 if(!game)return;el('score').textContent=game.score.toLocaleString();el('remaining').textContent=String(game.remaining);el('stars').textContent='★'.repeat(game.stars)||'—';el('goals').replaceChildren(...game.data.goals.map(g=>{const p=document.createElement('span');const label=g.type==='score'?text('Очки','Score'):g.type==='collect'?text('Тип ','Type ')+(g.color!+1):g.type==='obstacles'?text('Препятствия','Obstacles'):g.type==='delivery'?text('Доставка','Delivery'):text('Спецэлементы','Specials');p.textContent=`${label}: ${Math.min(game!.value(g),g.target)} / ${g.target}`;return p;}));
 el('boosters').replaceChildren();if(mode==='mission')for(const type of Object.keys(names) as Booster[]){const b=document.createElement('button');b.textContent=names[type]+' ×'+store.data.inventory[type];b.disabled=busy||store.data.inventory[type]<=0||game.over||(['rocket','bomb','lightning'].includes(type)&&game.moves>0);b.classList.toggle('armed',armed===type);b.onclick=()=>{armed=type;el('status').textContent=type==='shuffle'?'':text('Выбери клетку на поле.','Choose a cell.');if(type==='shuffle')void boost(0);else hud();};el('boosters').append(b);}for(const id of ['hint','restart','exit'])el<HTMLButtonElement>(id).disabled=busy;profile();terrain();
}
function select():void{el('selection').hidden=false;el('play').hidden=true;el('reward-screen').hidden=true;music.stop();el('heading').textContent=mode==='mission'?text('Миссии','Missions'):text('Головоломки','Puzzles');el('intro').textContent=mode==='mission'?text('Три главы. Тридцать заказов. Поможешь закрыть смену?','Three chapters. Thirty orders. Help us close the shift?'):text('Каждая задача имеет проверенное решение. Бустеры здесь не работают.','Every puzzle has a verified solution. No boosters.');el('levels').replaceChildren();
 for(const data of list()){if(mode==='mission'&&(data.id-1)%10===0){const h=document.createElement('h2');h.className='chapter';h.textContent=text('Глава ','Chapter ')+(1+Math.floor((data.id-1)/10));el('levels').append(h);}const b=document.createElement('button');const record=store.data.records[`${mode}:${data.id}`];b.textContent=`${data.id}. ${en?data.titleEn:data.title}`;const s=document.createElement('small');s.textContent=record?'★'.repeat(record.stars)+' · '+record.score:text('Ещё не пройдено','Not completed');b.append(s);b.disabled=!store.unlocked(mode,data.id);b.onclick=()=>{if(store.data.active&&!store.data.active.data.mode.includes('rank'))ask(()=>start(data),text('Заменить незавершённый уровень?','Replace your unfinished level?'));else start(data);};el('levels').append(b);}
 el('continue-level').hidden=!store.data.active;profile();
}
function start(data:LevelData,restore=false):void{game=restore&&store.data.active?Level.restore(store.data.active):new Level(data);mode=game.data.mode;shown=cloneBoard(game.board);selected=null;renderer.selected=null;renderer.hints=[];armed=null;renderer.paused=false;el('selection').hidden=true;el('play').hidden=false;el('reward-screen').hidden=true;el('level-title').textContent=`${data.id}. ${en?data.titleEn:data.title}`;el('status').textContent=text('Собери заказ до окончания ходов.','Complete all goals before moves run out.');renderer.draw(shown);hud();checkpoint();void audio.unlock();void music.start();if(game.over)finish();else if(!restore&&data.mode==='mission'&&(data.id-1)%10===0){el('story-copy').textContent=[text('До полуночи ещё тихо. Начнём с простых заказов, потом разберём поставку.','It is quiet before midnight. Start with a few orders, then unpack the delivery.'),text('Снаружи дождь, а у нас очередь. На складе лёд и коробки — освободи кухню.','Rain outside, a queue inside. Ice and boxes in the storeroom — clear the kitchen.'),text('Скоро рассвет. Остался последний рейс доставки. Закроем эту смену красиво.','Dawn is near. One last delivery run. Let’s finish this shift in style.')][Math.floor((data.id-1)/10)]!;dlg('story').showModal();}}
async function playback(events:ReturnType<Level['swap']>['events']):Promise<void>{if(!game)return;checkpoint();for(const event of events){while(renderer.paused)await new Promise<void>(r=>setTimeout(r,70));audio.play(event);await renderer.animate(shown!,event);shown=cloneBoard(event.board);}shown=cloneBoard(game.board);renderer.draw(shown);hud();}
function finish():void{if(!game?.over)return;music.stop();const reward=store.complete(mode,game.data.id,game.score,game.stars);if(!game.won){store.data.active=game.snapshot();store.save();}el('result-title').textContent=game.won?text('Заказ готов!','Order ready!'):text('Ходы закончились','No moves left');el('result-copy').textContent=`${'★'.repeat(game.stars)} · ${game.score} ${text('очков','points')} · +${reward.xp} XP · +${reward.caps} ◉`;el('next').hidden=!game.won||game.data.id>=list().length;dlg('result-dialog').showModal();profile();}
async function move(m:Move):Promise<void>{if(!game||busy||renderer.paused||game.over)return;busy=true;hud();renderer.selected=null;selected=null;renderer.hints=[];try{const result=game.swap(m);if(result.accepted){await playback(result.events);el('status').textContent=text('Хороший ход. Продолжай!','Good move. Keep going!');}else{audio.invalid();el('status').textContent=text('Здесь нет хода или клетка заблокирована.','No match, or a locked cell.');}}catch{el('status').textContent=text('Ход отменён. Попробуй другой.','Move rolled back. Try another.');}finally{busy=false;hud();lastInput=Date.now();finish();}}
async function boost(index:number):Promise<void>{if(!game||!armed||busy)return;const type=armed;armed=null;busy=true;hud();try{let color=0;if(type==='recolor'){const answer=prompt(text('Новый тип: 1–6','New type: 1–6'),'1');if(answer===null)return;color=Number(answer)-1;}const events=game.boost(type,index,color);store.spend(type);await playback(events);}catch{el('status').textContent=text('Бустер не применён. Выбери другую клетку.','Booster not used. Choose another cell.');}finally{busy=false;hud();finish();}}
function choose(i:number):void{if(busy||!game||renderer.paused)return;lastInput=Date.now();if(armed){void boost(i);return;}if(selected===null){selected=i;renderer.selected=i;renderer.draw(shown!);return;}const from:[number,number]=[selected%8,Math.floor(selected/8)],to:[number,number]=[i%8,Math.floor(i/8)];if(Math.abs(from[0]-to[0])+Math.abs(from[1]-to[1])===1)void move({from,to});else{selected=i;renderer.selected=i;renderer.draw(shown!);}}
const canvas=el<HTMLCanvasElement>('board');let down:{x:number;y:number;i:number}|null=null;
canvas.onpointerdown=e=>{if(busy||renderer.paused||e.button!==0)return;const r=canvas.getBoundingClientRect();const x=Math.floor((e.clientX-r.left)/r.width*8),y=Math.floor((e.clientY-r.top)/r.height*8);down={x:e.clientX,y:e.clientY,i:y*8+x};canvas.setPointerCapture(e.pointerId);};
canvas.onpointerup=e=>{if(!down)return;const d=down;down=null;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.max(Math.abs(dx),Math.abs(dy))>canvas.getBoundingClientRect().width/32){const from:[number,number]=[d.i%8,Math.floor(d.i/8)];const to:[number,number]=Math.abs(dx)>Math.abs(dy)?[from[0]+Math.sign(dx),from[1]]:[from[0],from[1]+Math.sign(dy)];void move({from,to});}else choose(d.i);};canvas.onpointercancel=()=>{down=null;};
canvas.onkeydown=e=>{if(busy||renderer.paused)return;const offsets:Record<string,number>={ArrowLeft:-1,ArrowRight:1,ArrowUp:-8,ArrowDown:8};if(e.key in offsets){e.preventDefault();if(e.key==='ArrowLeft'&&cursor%8===0||e.key==='ArrowRight'&&cursor%8===7)return;cursor=Math.max(0,Math.min(63,cursor+offsets[e.key]!));renderer.hints=[cursor];renderer.draw(shown!);}else if(e.key===' '||e.key==='Enter'){e.preventDefault();choose(cursor);}};
function pause():void{if(el('play').hidden||dlg('pause-dialog').open)return;renderer.paused=true;music.stop();void audio.suspend();checkpoint();dlg('pause-dialog').showModal();}
function resume():void{dlg('pause-dialog').close();renderer.paused=false;void audio.unlock();void music.start();}
function ask(action:()=>void,copy?:string):void{confirmAction=action;if(copy)el('confirm-copy').textContent=copy;dlg('confirm-dialog').showModal();}
el('story-close').onclick=()=>dlg('story').close();
el('pause').onclick=pause;el('resume').onclick=resume;dlg('pause-dialog').oncancel=e=>{e.preventDefault();resume();};el('exit').onclick=()=>{dlg('pause-dialog').close();checkpoint();select();};el('restart').onclick=()=>ask(()=>start(game!.data),text('Начать заново? Потраченные бустеры не возвращаются.','Restart? Spent boosters will not be returned.'));
el('confirm').onclick=()=>{dlg('confirm-dialog').close();confirmAction();};el('cancel').onclick=()=>dlg('confirm-dialog').close();
el('hint').onclick=()=>{if(!game||busy)return;const hint=game.hint();renderer.hints=hint?[hint.from[1]*8+hint.from[0],hint.to[1]*8+hint.to[0]]:[];renderer.draw(shown!);lastInput=Date.now();};
el('next').onclick=()=>{dlg('result-dialog').close();start(list()[game!.data.id]!);};el('retry').onclick=()=>{dlg('result-dialog').close();start(game!.data);};el('back').onclick=()=>{dlg('result-dialog').close();select();};
el('missions').onclick=()=>{if(busy)return;mode='mission';select();};el('puzzles').onclick=()=>{if(busy)return;mode='puzzle';select();};el('continue-level').onclick=()=>{if(store.data.active)start(store.data.active.data,true);};
function rewards():void{if(busy)return;music.stop();el('play').hidden=true;el('selection').hidden=true;el('reward-screen').hidden=false;el('inventory').replaceChildren();for(const type of Object.keys(names) as Booster[]){const b=document.createElement('button');b.textContent=`${names[type]} ×${store.data.inventory[type]} · ${type==='lightning'?60:20} ◉`;b.onclick=()=>{if(!store.buy(type))el('notice').textContent=text('Не хватает крышек.','Not enough caps.');rewards();};el('inventory').append(b);}const labels={first:text('Первый заказ','First order'),ten:text('Десять заказов','Ten orders'),stars:text('30 звёзд','30 stars'),puzzles:text('Все головоломки','All puzzles'),night:text('Смена закрыта','Shift complete')};el('achievements').replaceChildren(...Object.entries(labels).map(([id,label])=>{const p=document.createElement('p');p.textContent=(store.data.achievements.includes(id)?'✓ ':'○ ')+label;return p;}));profile();}
el('rewards').onclick=rewards;el('daily').onclick=()=>{el('notice').textContent=store.claimDaily()?text('+15 крышек!','+15 caps!'):text('Уже получено. Приходи завтра.','Already claimed. Come back tomorrow.');rewards();};el('reset-progress').onclick=()=>ask(()=>{store.reset();game=null;rewards();},text('Удалить весь прогресс миссий, награды и инвентарь?','Delete all campaign progress, rewards and inventory?'));
const lessons=[[text('Привет, я Рита!','Hi, I’m Rita!'),text('Меняй соседние предметы. Три одинаковых исчезают. Неверный ход не тратит попытку.','Swap neighboring items. Match three. Invalid swaps do not spend a move.')],[text('Спецзаказ','Special order'),text('4 в ряд — ракета; T или L — бомба; 5 — молния. Соединяй спецэлементы для мощных комбинаций.','Four makes a rocket; T/L a bomb; five a lightning. Combine specials for larger effects.')],[text('Препятствия','Obstacles'),text('Лёд и цепи: совпадение в клетке. Коробки, подносы и соус: совпадение рядом или взрыв. Цифра — прочность. Пакет ↓ должен опуститься вниз.','Ice and chains: match the covered tile. Boxes, trays and sauce: match nearby or blast. Number means durability. Deliver ↓ parcels to the bottom.')],[text('Твоя смена','Your shift'),text('Выполни все цели за отведённые ходы. Звёзды открывают главы. В головоломках старт всегда одинаковый, бустеры запрещены.','Complete every goal within the move limit. Stars unlock chapters. Puzzles always start the same and have no boosters.')]];let lesson=0;
function teach():void{el('tutorial-title').textContent=lessons[lesson]![0]!;el('tutorial-copy').textContent=lessons[lesson]![1]!;if(!dlg('tutorial').open)dlg('tutorial').showModal();}el('help').onclick=()=>{if(!el('play').hidden)pause();lesson=0;teach();};el('tutorial-next').onclick=()=>{if(++lesson<lessons.length)teach();else{dlg('tutorial').close();store.data.tutorial=true;store.save();}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('pagehide',()=>{checkpoint();music.stop();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!el('play').hidden&&!document.querySelector('dialog[open]')){e.preventDefault();pause();}});
setInterval(()=>{if(game&&!busy&&!renderer.paused&&!el('play').hidden&&Date.now()-lastInput>10000){let hints=true;try{hints=JSON.parse(localStorage.getItem('nightshift.basic.v1')??'{}').settings?.hints!==false;}catch{/* Default. */}if(hints)el('hint').click();}},1000);
if(en){document.documentElement.lang='en';const labels:Record<string,string>={missions:'Missions',puzzles:'Puzzles',rewards:'Rewards',pause:'Pause',resume:'Continue',exit:'Levels',hint:'Hint',restart:'Restart',next:'Next',retry:'Retry',back:'Levels',confirm:'Yes',cancel:'Cancel','continue-level':'Continue level','score-label':'Score','moves-label':'Moves left','reward-title':'Rewards',daily:'Claim daily reward','inventory-label':'Inventory','achievements-label':'Achievements','reset-progress':'Reset progress','tutorial-next':'Next','pause-heading':'Paused','confirm-heading':'Confirm'};for(const [id,label] of Object.entries(labels))el(id).textContent=label;}
el('legend').textContent=text('Голубой — лёд · коричневый — коробка · серый — поднос · пунктир — цепь · красный — соус. Цифра — прочность.','Blue: ice · brown: box · gray: tray · dashed: chain · red: sauce. Number: durability.');
try{const responses=await Promise.all([fetch('./data/missions.json'),fetch('./data/puzzles.json')]);if(responses.some(r=>!r.ok))throw Error('Load failed');missions=(await responses[0]!.json() as unknown[]).map(validateLevel);puzzles=(await responses[1]!.json() as unknown[]).map(validateLevel);select();if(!store.data.tutorial)teach();}catch{el('notice').textContent=text('Не удалось загрузить уровни. Перезагрузи страницу при подключении к сети.','Could not load levels. Reload when online.');}
