import test from 'node:test';
import assert from 'node:assert/strict';
import { StorageService, defaults } from '../../dist/app/StorageService.js';
import { Game } from '../../dist/game/core/index.js';
function memory(){const data=new Map();return {getItem:key=>data.get(key)??null,setItem:(key,value)=>data.set(key,value)};}
test('Endless save survives reload and continues the same RNG stream',()=>{const store=memory(),service=new StorageService(store),game=new Game(91);game.swap(game.hint());const profile={version:1,settings:{...defaults,language:'en'},best:game.score,session:{game:game.snapshot(),elapsed:12345}};assert.equal(service.save(profile),true);const restored=new StorageService(store).load();assert.deepEqual(restored,profile);const next=Game.restore(restored.session.game);assert.deepEqual(next.swap(next.hint()),game.swap(game.hint()));});
test('corrupted storage recovers without throwing or silently replacing the original',()=>{const store=memory();store.setItem(StorageService.key,'broken');const service=new StorageService(store);assert.equal(service.load().session,null);assert.equal(service.error,true);assert.equal(store.getItem(StorageService.key),'broken');});
test('unavailable storage reports save failure while keeping the in-memory session',()=>{const service=new StorageService({getItem(){throw Error('blocked');},setItem(){throw Error('quota');}});const profile=service.load();profile.session={game:new Game(9).snapshot(),elapsed:0};assert.equal(service.save(profile),false);assert.equal(service.error,true);assert.equal(profile.session.game.seed,9);});
test('invalid settings, board and elapsed are rejected',()=>{for(const change of [p=>{p.settings.master=101;},p=>{p.session.elapsed=-1;},p=>{p.session.game.board.cells[0]=9999;},p=>{p.version=2;}]){const store=memory();const p={version:1,settings:{...defaults},best:0,session:{game:new Game(10).snapshot(),elapsed:0}};change(p);store.setItem(StorageService.key,JSON.stringify(p));const service=new StorageService(store);assert.equal(service.load().session,null);assert.equal(service.error,true);}});
test('new session preserves best score and settings',()=>{const service=new StorageService(memory());const p=service.load();p.best=9000;p.settings.reduced=true;p.session={game:new Game(42).snapshot(),elapsed:0};service.save(p);assert.equal(service.load().best,9000);assert.equal(service.load().settings.reduced,true);});
